parameters:
- name: azure_resource_group
  type: string
- name: kubernetes_cluster
  type: string
- name: azure_container_registry
  type: string
- name: acr_username
  type: string
- name: acr_password
  type: string
- name: chart_name
  type: string
- name: chart_version
  type: string
- name: acr_tenant
  type: string
- name: release_name
  type: string
- name: env
  type: string
- name: sub_product_name
  type: string
  default: default
- name: container_image
  type: string
- name: client_id
  type: string

steps:
- bash: |
    helm registry login ${{ parameters.azure_container_registry }} --username ${{ parameters.acr_username }} --password ${{ parameters.acr_password }}
    helm pull oci://${{ parameters.azure_container_registry }}/helm/${{ parameters.chart_name }} --version ${{ parameters.chart_version }} -d $(Build.ArtifactStagingDirectory)  
  displayName: Helm pull 
- task: HelmDeploy@0
  displayName: Helm install
  inputs:
    kubernetesServiceEndpoint: SC-${{ parameters.sub_product_name }}-${{ parameters.env }}
    azureResourceGroup: ${{ parameters.azure_resource_group }}
    kubernetesCluster: ${{ parameters.kubernetes_cluster }}
    command: upgrade
    releaseName: ${{ parameters.release_name }}
    arguments: --namespace ${{ parameters.sub_product_name }}-${{ parameters.env }} --set image.repository=${{ parameters.container_image }} --set env=${{ parameters.env }} --set identity.client_id=${{ parameters.client_id }}
    chartType: FilePath
    chartPath: $(Build.ArtifactStagingDirectory)/${{ parameters.chart_name }}-${{ parameters.chart_version }}.tgz
    connectionType: kubernetesServiceEndpoint
    install: true
    waitForExecution: false