module "appconfig" {
  source                              = "app.terraform.io/csiseg/appconfig/csi"
  version                             = "1.0.1"
  name                                = "appcs-fdxaccounts-ebg-${var.env}-${var.loc}"
  resource_group_name                 = module.resourcegroup.name
  location                            = module.resourcegroup.location
  sku                                 = var.appconfig_sku
  identity_type                       = var.appconfig_identity_type
  user_assigned_identity_resource_ids = [module.azuremanagedidentity.mi_id]
   keys = [
    { key  = var.appconfig
      type = var.type
    value = var.appconfig_value },
    { key = var.appconfig_1
      type = var.type 
      value = var.appconfig_value_1},    
    { key  = var.appconfig_2
      type = var.type
    value = var.appconfig_value_2 },
    { key  = var.appconfig_3
      type = var.type
    value = var.appconfig_value_3 },
    { key = var.appconfig_4
     type = var.type
     value = var.appconfig_value_4 },
    { key = var.appconfig_5
      type = var.type
      value = var.appconfig_value_5 },
    { key = var.appconfig_6
      type = var.type
      value = var.appconfig_value_6},
    { key = var.appconfig_7
     type = var.type
     value = var.appconfig_value_7},
    { key = var.appconfig_8
      type = var.type
      value = var.appconfig_value_8 },
    { key = var.appconfig_9
      type = var.type
      value = var.appconfig_value_9 },
    { key = var.appconfig_10
      type = var.type 
      value = var.appconfig_value_10},
    { key = var.appconfig_11
      type = var.type 
      value = var.appconfig_value_11},
    { key = var.appconfig_12
      type = var.type
      value = var.appconfig_value_12}
  ]
  tags       = local.tags
  depends_on = [module.resourcegroup]
}
