{{- range $namespaces := .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespaces.name }}
  labels:
    app: {{ $.Values.app.name }}
    istio-injection: enabled
---
{{- end }}

{{- range $namespace := .Values.namespaces }}                                                                               
{{- range $serviceaccount := $namespace.serviceaccounts }}                                                                                  
---                                                                                                                         
apiVersion: v1                                                                                                            
kind: ServiceAccount                                                                                                                
metadata:                                                                                                                   
  name: {{ $serviceaccount }}                                        
  namespace: {{ $namespace.name }} 
  annotations:
    azure.workload.identity/client-id: 'de5bb527-2f09-417a-a624-c20d1ab23147'
  labels:
    azure.workload.identity/use: "true"                                                                                                                                                                                           
---                                                                                                                        
{{- end }}                                                                                                                  
{{- end }}