---
parameters:
- name: container_registry
  type: string
- name: acr_url
  type: string
- name: docker_repository
  type: string
# docker
- name: build_context
  type: string
- name: dockerfile_path
  type: string
- name: risk_profile
  type: string
- name: twistlock_id
  type: string
- name: twistlock_password
  type: string
- name: build_flags
  type: string
  default: ""

steps:
- task: Docker@2
  displayName: 'Docker Build'
  inputs:
    command: build
    containerRegistry: ${{ parameters.container_registry }}
    repository: ${{ parameters.docker_repository }}
    buildContext: ${{ parameters.build_context }}
    dockerfile: ${{ parameters.dockerfile_path }}
    arguments: --build-arg BuildId=$(Build.BuildId) --label "risk.profile=${{ parameters.risk_profile }} ${{ parameters.build_flags }}"
    tags: $(Build.BuildNumber)
- template: ../twistlock/scan.yaml
  parameters:
    image_with_tag: ${{ parameters.acr_url }}/${{ parameters.docker_repository }}:$(Build.BuildNumber)
    twistlock_project: $(System.TeamProject)
    twistlock_id: ${{ parameters.twistlock_id }}
    twistlock_password: '${{ parameters.twistlock_password }}'
    ignore_failed_scan: ${{ and(ne(variables['Build.SourceBranchName'], 'main'), ne(variables['Build.SourceBranchName'], 'master')) }}
- task: Docker@2
  displayName: 'Docker Push'
  inputs:
    containerRegistry: ${{ parameters.container_registry }}
    repository: ${{ parameters.docker_repository }}
    command: 'push'
    tags: $(Build.BuildNumber)