---
name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: application-pipeline-templates
    type: git
    name: EBG DevOps/application-pipeline-templates   

jobs:
- job:
  steps:
  - template : /application/nodejs/test.yaml@application-pipeline-templates
    parameters:
      working_dir: $(Build.SourcesDirectory)/application/nodejs/test-example